defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/hexwarriors_dev
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/hexwarriors_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/hexwarriors_production
    <<: *defaults